const snackbarsTypes = {
    DRAGON_SELECT: 'DRAGON_SELECT',
    MATCH_OCCUR: 'MATCH_OCCUR',
    ADD_SNACKBAR: 'ADD_SNACKBAR',
    SET_SNACK_LOG: 'SET_SNACK_LOG',
    ADD_TO_COUNTER: 'ADD_TO_COUNTER',
    REDUCE_FROM_COUNTER: 'REDUCE_FROM_COUNTER',
    ADD_TO_COUNTER_ASYNC: 'ADD_TO_COUNTER_ASYNC',
}

export default snackbarsTypes